### ISSUE TITLE
Python Library for Ponoor

### ISSUE THREAD

**Issue by JulianOrteil** [ponoor/STEP400#15]
Good day @kanta and other maintainers/contributors of this project.

I must give my thanks and appreciation for developing such a project as this. Recently, I have purchased a STEP400 motor controller for a small project of mine; however, I did notice a lack of a library for interfacing with this device--specifically in Python. As my program is written entirely in Python, would you be opposed to me developing a library for this device? I plan on it doing nothing more than presenting your OSC endpoints (like `/getVersion`) in a Pythonic interface.

I am specifically asking for permission to use the name "ponoor" in it (like "python-ponoor", or "ponoor-step400, "ponoor-step800", etc).

Please do let me know your thoughts or concerns.
Jules

**Comment by kanta** [comment]
Hi @JulianOrteil , that would be amazing! I haven't used Python much personally, but I can see how it could be a useful library for many users!
For the name, "Ponoor" is a name of a company so there are possibilities to release another products in the future. How about "python-step-series"? I have used this name to some other repos.
https://github.com/ponoor/step-series-support

Thanks for your idea and choosing STEP400!
kanta

**Comment by JulianOrteil** [comment]
Hey kanta, great to know you're on board!

I have absolutely no issue with using a name such as that.

Because this library would be specifically for your Step-series products, I believe it would be most appropriate if the library were to live under your 'ponoor' organization. If you're able, could you please create an empty repository with the "python-step-series" name you suggested, and give me full-contributor access to it?

If not, I have no problem with it living under my account.
Jules

**Comment by kanta** [comment]
Sounds perfect for me! I will create the repo and invite you to edit.
I have a question. There are some coding example repos for step series like this;
https://github.com/ponoor/step-series-example-openFrameworks
What do you think would be an appropriate name for the new repository? `step-series-example-Python` or `step-series-library-Python`?

**Comment by JulianOrteil** [comment]
Typically, in Python--as I'm sure other languages--you don't need to to specify your library as a library in the name. Also, when I see "example", I believe it to be just an example application that I can run, not an API.

At any rate, I think your first suggestion of `python-step-series` is perfect. You can see other examples of this naming scheme here: https://pypi.org/search/?q=python-&o=

**Comment by kanta** [comment]
Ok! `python-step-series` seems to be the most appropriate name. I have just create it and invite you. Thank you very much for your contribution!
https://github.com/ponoor/python-step-series

**Comment by JulianOrteil** [comment]
I will get started right away. :+1:
