### ISSUE TITLE
[Docs] Tutorial

### ISSUE THREAD

**Issue by kanta** [ponoor/STEP400#2]
https://ponoor.com/en/docs/step400/tutorial/
プロトタイプからコネクタが変更になったことに合わせて、日本語版で下記部分を変更しました。また僕のほうで英文を入れてみています。

旧
STEP400の電源コネクタは大容量の電源を接続することを想定していますが、小さなモータを回す場合は下の写真のような変換コネクタを使ってACアダプタを接続すると便利です。このコネクタは電子パーツ店やAmazonなどで入手可能です。上の例に出てきたモータを1台回す場合は、ACアダプタの容量は24V1Aあれば十分です。

写真では両端に専用の端子を圧着して使っていますが、両端を剥いてはんだを流しただけの状態でも使用可能です。

新
上の例に出てきたモータを1台回す場合は、ACアダプタの容量は24V1Aあれば十分です。STEP400に接続可能なのは、外径5.5mm, 内径2.1mmでセンタープラスのACアダプタです。

If you want to run a single motor in the example above, the AC adapter’s capacity of 24V1A is sufficient. Applicable AC adapters are which have 5.5mm outer diameter / 2.1mm inner diameter / center positive connector.

そのほか、以下の英文を追加しています（堀尾訳、要修正です）。

To simplify this tutorial, we will assume that the PC and the board are connected peer to peer with Ethernet cable. You can of course also go through a network switch (NOT a router) instead. Routers can make things complicated when they have DHCP functionality, not recommended to get started.

You can set individual KVALs for example with `/setRunKval` for `KVAL_RUN` but we are going to try following command which can set 4 KVALs at once.

**Comment by kanta** [comment]
とりあえず上記の文章は、未チェック英文のメモです！

**Comment by yuskegoto** [comment]
DCバレルジャック／プラグは英語でもDC barrel jack / plug なので、そのようにしては。またApplicableはあまり自然はない気がしますので power supply must have .... としてみました。以下のような感じでいかがでしょうか？
If you want to run a single motor in the example above, the AC adapter’s capacity of 24V1A is sufficient. **The power supply** must have **DC barrel plug** with 5.5mm outer diameter / 2.1mm inner diameter / center positive.

**Comment by kanta** [comment]
ありがとうございます！更新しました。
https://ponoor.com/en/docs/step400/tutorial/
