### ISSUE TITLE
[Docs] Power supply and Motor

### ISSUE THREAD

**Issue by kanta** [ponoor/STEP400#3]
旧
ターミナルには4つのねじ式端子があり、左手の2個がマイナス、右手の2個がプラスの端子です。

新
STEP400にはDCジャック(4)と、ねじ式端子(5)の2種類の電源端子があります。
<img src="https://ponoor.com/cms/wp-content/uploads/2020/10/step400_connectors_numbering.jpg" width="600" />
DCジャックは
- 外径5.5mm
- 内径2.1mm
- センタープラス

のコネクタが適合します。DCジャックの定格は24V5Aです。それを超える電圧および電流で使用する場合は、ねじ式ターミナルを使用してください。

ねじ式ターミナルは、基板端面から見て左がマイナス、右側がプラスの端子です。各端子のねじ径はM3です。直接ケーブルの芯線を締めこむこともできますが、専用の端子を使うとより確実に接続できます。

---

There are 2 types of power input ternaminals on STEP400, a DC jack (4) and a screw terminal(5).
<img src="https://ponoor.com/cms/wp-content/uploads/2020/10/step400_connectors_numbering.jpg" width="600" />

For the DC jack, a connector which has
- 5.5mm outer diameter
- 2.1mm inner diameter
- center positive

will be applicable. The rateing of the DC jack are limited to 24V/5A. Use the screw terminal if you want to apply bigger voltage or current than that.

For the screw terminal, if you see the connector from the edge of the board, left side is negative, right side is positive terminal. The screw diameter is M3. You can fasten the cupper wire directly, but you can also use a dedicated terminal for a more secure connection.

**Comment by yuskegoto** [comment]
以下のようにしてはいかがでしょうか？
For the DC barrel plug, use a DC barrel plug with following specifications

- 5.5mm outer diameter
- 2.1mm inner diameter
- center positive

The rating of the DC jack are limited to 24V/5A. Use the screw terminal if you want to supply larger voltage or current.

**Comment by kanta** [comment]
こちらも #2 でご指摘いただいた部分のバリエーションですね。こういう細かな部分まで見ていただいてとても助かります！ありがとうございます。こちらもアップデートしましたー。
